version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - db-service
      - backend-s3-api
      - backend-db-api

  backend-s3-api:
    build:
      context: ./backend/s3-api
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: us-east-1
    depends_on:
      - db-service

  backend-db-api:
    build:
      context: ./backend/db-api
    ports:
      - "8081:8081"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: auth_db
    depends_on:
      - db-service

  db-service:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: auth_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
